### ISSUE TITLE
Bug with "New Test" button in GUI

### ISSUE THREAD

**Issue by asreimer** [DPastl/GliderFlightTest#1]
This is the traceback I get when clicking the new test button:

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib64/python2.7/lib-tk/Tkinter.py", line 1536, in __call__
    return self.func(*args)
  File "exam_gui.py", line 161, in answer_question
    if self._exam.answer_list[self._exam.current_question_index] is not None:
IndexError: list index out of range
```

**Comment by asreimer** [comment]
This was fixed in commit. Specifically[ this one](https://github.com/DPastl/GliderFlightTest/commit/ed536eccf586a2347a7b5b3644cd6a7e3f30b22b).
